### ISSUE TITLE
Use with Docker API

### ISSUE THREAD

**Issue by davedoesdev** [ClusterHQ/flocker-docker-plugin#25]
I have a quick question regarding the flocker docker plugin.
I should be able to use it if I'm not using Compose, right?
I intend to drive each host's Docker API (using Salt) - flocker should take care of ensuring volumes follow containers around?

**Comment by lukemarsden** [comment]
Yep, this should work just fine.

If AWS is an option for you, you might like to try the new installer at http://doc-dev.clusterhq.com/labs/installer.html - I'd be interested in your feedback!

**Comment by davedoesdev** [comment]
@lukemarsden I'm looking to add flocker to my Linux distribution ([heddle](https://github.com/davedoesdev/heddle) and [dobby](https://github.com/davedoesdev/dobby)) so I'm afraid I won't be using that installer.
But I may well need help as I go. Where's the best place to ping you?

**Comment by lukemarsden** [comment]
Cool! Come hang out on #clusterhq on Freenode. I'm `lewq` there.

**Comment by davedoesdev** [comment]
Closing - I have flocker compiled. I just need a non-zfs driver (I'm using btrfs). Ceph would be ideal.
